# Generated by Django 4.1.7 on 2023-03-25 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_course_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='slug',
            new_name='co_slug',
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
