# Generated by Django 4.1.7 on 2023-04-27 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_usercourse_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
